export const manualItems =[
    {
        "title":"Before",
        "items":[
            "2","3","4","5"
        ],
    },
    {
        "title":"Receptionist",
        "items":[
            "6","7","8","9","10","11"
        ],
    },
    {
        "title":"in_store",
        "items":[
            "12","13"
        ],
    },
    {
        "title":"ApprochMethod",
        "items":[
            "14","15","16","17"
        ],
    },
    {
        "title":"Advanced",
        "items":[
            "18","19","20","21"
        ],
    },
    {
        "title":"AwayOut",
        "items":[
            "22"
        ],
    },
    {
        "title":"Retirement",
        "items":[
            "23","24","25"
        ],
    },
]